### ISSUE TITLE
Prusa MK3S Flashing failed, Error opening serial device

### ISSUE THREAD

**Issue by wasyl00** [OctoPrint/OctoPrint-FirmwareUpdater#179]
**Hardware Setup**
Prusa MK3S connected to Octoprint on Rpi3 directly to Einsy Rambo via J19 pins. 

**Describe the problem**
I have a problem with using this plugin when trying to flash firmware I get error "Flashing failed Error opening serial device"
Octoprint works just fine, just the flashing fails. I tried two available serial port in options (see errors in the log files). Any suggestion?

Below are my settings: 
https://i.imgur.com/vJnMzB4.png

**Log Files**
**Firmware updater log:**
`2021-01-13 13:03:34,944 /usr/bin/avrdude -v -q -p m2560 -c arduino -P dev/ttyAMA0 -D -U flash:w:/tmp/tmpHID1Xr:i
2021-01-13 13:03:35,694 > 
2021-01-13 13:03:35,696 > avrdude: Version 6.3-20171130
2021-01-13 13:03:35,697 >          Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
2021-01-13 13:03:35,699 >          Copyright (c) 2007-2014 Joerg Wunsch
2021-01-13 13:03:35,700 > 
2021-01-13 13:03:35,701 >          System wide configuration file is "/etc/avrdude.conf"
2021-01-13 13:03:35,706 >          User configuration file is "/home/pi/.avrduderc"
2021-01-13 13:03:35,707 >          User configuration file does not exist or is not a regular file, skipping
2021-01-13 13:03:35,709 > 
2021-01-13 13:03:35,710 >          Using Port                    : dev/ttyAMA0
2021-01-13 13:03:35,712 >          Using Programmer              : arduino
2021-01-13 13:03:35,713 > avrdude: ser_open(): can't open device "dev/ttyAMA0": No such file or directory
2021-01-13 13:03:35,727 > 
2021-01-13 13:03:35,730 > avrdude done.  Thank you.
2021-01-13 13:03:35,733 > 
2021-01-13 13:03:35,735 > 
2021-01-13 13:03:53,280 
2021-01-13 13:03:53,311 /usr/bin/avrdude -v -q -p m2560 -c wiring -P dev/ttyAMA0 -D -U flash:w:/tmp/tmpww6N9Y:i
2021-01-13 13:03:54,092 > 
2021-01-13 13:03:54,094 > avrdude: Version 6.3-20171130
2021-01-13 13:03:54,096 >          Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
2021-01-13 13:03:54,097 >          Copyright (c) 2007-2014 Joerg Wunsch
2021-01-13 13:03:54,099 > 
2021-01-13 13:03:54,101 >          System wide configuration file is "/etc/avrdude.conf"
2021-01-13 13:03:54,103 >          User configuration file is "/home/pi/.avrduderc"
2021-01-13 13:03:54,104 >          User configuration file does not exist or is not a regular file, skipping
2021-01-13 13:03:54,106 > 
2021-01-13 13:03:54,107 >          Using Port                    : dev/ttyAMA0
2021-01-13 13:03:54,109 >          Using Programmer              : wiring
2021-01-13 13:03:54,110 > avrdude: ser_open(): can't open device "dev/ttyAMA0": No such file or directory
2021-01-13 13:03:54,111 > ioctl("TIOCMGET"): Inappropriate ioctl for device
2021-01-13 13:03:54,112 > ioctl("TIOCMGET"): Inappropriate ioctl for device
2021-01-13 13:03:54,113 > 
2021-01-13 13:14:09,500 
2021-01-13 13:14:09,506 /usr/bin/avrdude -v -q -p m2560 -c wiring -P /dev/ttyS0 -D -U flash:w:/tmp/tmppP4ACS:i
2021-01-13 13:14:10,259 > 
2021-01-13 13:14:10,272 > avrdude: Version 6.3-20171130
2021-01-13 13:14:10,292 >          Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
2021-01-13 13:14:10,304 >          Copyright (c) 2007-2014 Joerg Wunsch
2021-01-13 13:14:10,312 > 
2021-01-13 13:14:10,320 >          System wide configuration file is "/etc/avrdude.conf"
2021-01-13 13:14:10,329 >          User configuration file is "/home/pi/.avrduderc"
2021-01-13 13:14:10,332 >          User configuration file does not exist or is not a regular file, skipping
2021-01-13 13:14:10,335 > 
2021-01-13 13:14:10,337 >          Using Port                    : /dev/ttyS0
2021-01-13 13:14:10,340 >          Using Programmer              : wiring
2021-01-13 13:14:10,340 > avrdude: ser_open(): can't set attributes for device "/dev/ttyS0": Inappropriate ioctl for device
2021-01-13 13:14:10,341 > ioctl("TIOCMGET"): Bad file descriptor
2021-01-13 13:14:10,341 > ioctl("TIOCMGET"): Bad file descriptor
2021-01-13 13:14:10,342 > avrdude: ser_drain(): select(): Bad file descriptor
2021-01-13 13:14:10,343 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,343 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,344 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,344 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,345 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,346 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,349 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,350 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,351 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,352 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,353 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,354 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,355 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,355 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,356 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,356 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,357 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,358 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,358 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,359 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,359 > avrdude: ser_send(): write error: Bad file descriptor
2021-01-13 13:14:10,360 > avrdude: stk500_send(): failed to send command to serial port
2021-01-13 13:14:10,361 > avrdude: ser_recv(): select(): Bad file descriptor
2021-01-13 13:14:10,361 > avrdude: stk500v2_ReceiveMessage(): timeout
2021-01-13 13:14:10,362 > avrdude: stk500v2_getsync(): timeout communicating with programmer
2021-01-13 13:14:10,363 > 
2021-01-13 13:14:10,363 > avrdude done.  Thank you.
2021-01-13 13:14:10,364 > `

**Octoprint log:**
`021-01-13 13:03:34,758 - octoprint.plugins.firmwareupdater - INFO - Firmware update started
2021-01-13 13:03:34,768 - octoprint.plugins.firmwareupdater - INFO - Disconnecting from printer
2021-01-13 13:03:34,921 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2021-01-13 13:03:34,933 - octoprint.plugins.firmwareupdater - INFO - Running '/usr/bin/avrdude -v -q -p m2560 -c arduino -P dev/ttyAMA0 -D -U flash:w:/tmp/tmpHID1Xr:i' in /usr/bin
2021-01-13 13:03:34,948 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-01-13 13:03:35,751 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Error opening serial device.
2021-01-13 13:03:35,763 - octoprint.plugins.firmwareupdater - INFO - Reconnecting to printer: port=dev/ttyAMA0, baudrate=115200, profile={'heatedChamber': False, 'name': 'Prusa i3 MK3', 'color': 'default', 'axes': {'y': {'speed': 6000, 'inverted': False}, 'x': {'speed': 6000, 'inverted': False}, 'z': {'speed': 200, 'inverted': False}, 'e': {'speed': 300, 'inverted': False}}, 'heatedBed': True, 'volume': {'origin': 'lowerleft', 'formFactor': 'rectangular', 'depth': 210.0, 'width': 250.0, 'custom_box': {'z_min': 0.0, 'y_min': -4.0, 'x_max': 250.0, 'x_min': 0.0, 'y_max': 210.0, 'z_max': 200.0}, 'height': 200.0}, 'model': 'Prusa i3 MK3', 'id': '_default', 'extruder': {'count': 1, 'nozzleDiameter': 0.4, 'offsets': [(0.0, 0.0)], 'sharedNozzle': False}}
2021-01-13 13:03:35,994 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial connection"
2021-01-13 13:03:36,017 - octoprint.util.comm - INFO - Connecting to port dev/ttyAMA0, baudrate 115200
2021-01-13 13:03:36,038 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial connection" to "Connecting"
2021-01-13 13:03:36,064 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:36,081 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:36,094 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2021-01-13 13:03:36,120 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:36,158 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2021-01-13 13:03:36,161 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2021-01-13 13:03:36,452 - octoprint.util.comm - INFO - Printer reports firmware name "Prusa-Firmware 3.9.3 based on Marlin"
2021-01-13 13:03:51,105 - octoprint.plugins.excluderegion - INFO - Setting update detected: g90InfluencesExtruder=False, clearRegionsAfterPrintFinishes=False, mayShrinkRegionsWhilePrinting=False, loggingMode=octoprint, enteringExcludedRegionGcode=None, exitingExcludedRegionGcode=None, extendedExcludeGcodes={'M73': {"gcode": "M73", "type": "ExcludedGcode", "mode": "merge", "description": "Suppress progress updates while excluding and output the most recent progress values encountered when exiting the excluded area"}, 'M117': {"gcode": "M117", "type": "ExcludedGcode", "mode": "last", "description": "Suppress display messages while excluding and output the last message encountered when exiting the excluded area"}, 'G4': {"gcode": "G4", "type": "ExcludedGcode", "mode": "exclude", "description": "Ignore all dwell commands in an excluded area to reduce delays while excluding"}, 'M205': {"gcode": "M205", "type": "ExcludedGcode", "mode": "merge", "description": "Record advanced setting changes while excluding and apply the most recent values in a single command after exiting the excluded area"}, 'M204': {"gcode": "M204", "type": "ExcludedGcode", "mode": "merge", "description": "Record default acceleration changes while excluding and apply the most recent values in a single command after exiting the excluded area"}}, atCommandActions={'ExcludeRegion': [{"action": "enable_exclusion", "type": "AtCommandAction", "command": "ExcludeRegion", "parameterPattern": "^\\s*(enable|on)(\\s|$)", "description": "Default action to enable exclusion"}, {"action": "disable_exclusion", "type": "AtCommandAction", "command": "ExcludeRegion", "parameterPattern": "^\\s*(disable|off)(\\s|$)", "description": "Default action to disable exclusion"}]}
2021-01-13 13:03:53,097 - octoprint.plugins.firmwareupdater - INFO - Firmware update started
2021-01-13 13:03:53,105 - octoprint.plugins.firmwareupdater - INFO - Disconnecting from printer
2021-01-13 13:03:53,224 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2021-01-13 13:03:53,248 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-01-13 13:03:53,275 - octoprint.plugins.firmwareupdater - INFO - Running '/usr/bin/avrdude -v -q -p m2560 -c wiring -P dev/ttyAMA0 -D -U flash:w:/tmp/tmpww6N9Y:i' in /usr/bin
2021-01-13 13:03:54,119 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Error opening serial device.
2021-01-13 13:03:54,125 - octoprint.plugins.firmwareupdater - INFO - Reconnecting to printer: port=dev/ttyAMA0, baudrate=115200, profile={'heatedChamber': False, 'name': 'Prusa i3 MK3', 'color': 'default', 'axes': {'y': {'speed': 6000, 'inverted': False}, 'x': {'speed': 6000, 'inverted': False}, 'z': {'speed': 200, 'inverted': False}, 'e': {'speed': 300, 'inverted': False}}, 'heatedBed': True, 'volume': {'origin': 'lowerleft', 'formFactor': 'rectangular', 'depth': 210.0, 'width': 250.0, 'custom_box': {'z_min': 0.0, 'y_min': -4.0, 'x_max': 250.0, 'x_min': 0.0, 'y_max': 210.0, 'z_max': 200.0}, 'height': 200.0}, 'model': 'Prusa i3 MK3', 'id': '_default', 'extruder': {'count': 1, 'nozzleDiameter': 0.4, 'offsets': [(0.0, 0.0)], 'sharedNozzle': False}}
2021-01-13 13:03:54,350 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial connection"
2021-01-13 13:03:54,357 - octoprint.util.comm - INFO - Connecting to port dev/ttyAMA0, baudrate 115200
2021-01-13 13:03:54,394 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial connection" to "Connecting"
2021-01-13 13:03:54,415 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:54,435 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:54,448 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2021-01-13 13:03:54,479 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-13 13:03:54,542 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2021-01-13 13:03:54,596 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2021-01-13 13:03:54,818 - octoprint.util.comm - INFO - Printer reports firmware name "Prusa-Firmware 3.9.3 based on Marlin"
2021-01-13 13:14:09,315 - octoprint.plugins.firmwareupdater - INFO - Firmware update started
2021-01-13 13:14:09,317 - octoprint.plugins.firmwareupdater - INFO - Disconnecting from printer
2021-01-13 13:14:09,451 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2021-01-13 13:14:09,473 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-01-13 13:14:09,491 - octoprint.plugins.firmwareupdater - INFO - Running '/usr/bin/avrdude -v -q -p m2560 -c wiring -P /dev/ttyS0 -D -U flash:w:/tmp/tmppP4ACS:i' in /usr/bin
2021-01-13 13:14:10,365 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Timeout communicating with programmer.
2021-01-13 13:14:10,370 - octoprint.plugins.firmwareupdater - INFO - Reconnecting to printer: port=dev/ttyAMA0, baudrate=115200, profile={'heatedChamber': False, 'name': 'Prusa i3 MK3', 'color': 'default', 'axes': {'y': {'speed': 6000, 'inverted': False}, 'x': {'speed': 6000, 'inverted': False}, 'z': {'speed': 200, 'inverted': False}, 'e': {'speed': 300, 'inverted': False}}, 'heatedBed': True, 'volume': {'origin': 'lowerleft', 'formFactor': 'rectangular', 'depth': 210.0, 'width': 250.0, 'custom_box': {'z_min': 0.0, 'y_min': -4.0, 'x_max': 250.0, 'x_min': 0.0, 'y_max': 210.0, 'z_max': 200.0}, 'height': 200.0}, 'model': 'Prusa i3 MK3', 'id': '_default', 'extruder': {'count': 1, 'nozzleDiameter': 0.4, 'offsets': [(0.0, 0.0)], 'sharedNozzle': False}}
2021-01-13 13:14:10,482 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial connection"
2021-01-13 13:14:10,498 - octoprint.util.comm - INFO - Connecting to port dev/ttyAMA0, baudrate 115200
2021-01-13 13:14:10,523 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial connection" to "Error: Connection error, see Terminal tab"
2021-01-13 13:14:10,535 - octoprint.plugins.excluderegion - INFO - Printing stopped: event=Error
2021-01-13 13:14:10,541 - octoprint.util.comm - INFO - Changing monitoring state from "Error: Connection error, see Terminal tab" to "Offline (Error: Connection error, see Terminal tab)"
2021-01-13 13:14:10,554 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port dev/ttyAMA0, baudrate 115200 from hook default: SerialException: '[Errno 11] Could not exclusively lock port dev/ttyAMA0: [Errno 11] Resource temporarily unavailable' @ comm.py:_open_serial:3670
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3670, in _open_serial
    settings().getFloat(["serial", "timeout", "connection"]),
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3644, in default
    serial_obj.open()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/serial/serialposix.py", line 312, in _reconfigure_port
    raise SerialException(msg.errno, "Could not exclusively lock port {}: {}".format(self._port, msg))
SerialException: [Errno 11] Could not exclusively lock port dev/ttyAMA0: [Errno 11] Resource temporarily unavailable
2021-01-13 13:14:10,558 - octoprint.plugins.action_command_notification - INFO - Notifications cleared`

**Additional context**
N/A

**Comment by wasyl00** [comment]
Post duplicated due to 404 error, please disregard.
