### ISSUE TITLE
pyserial>=3.4,<3.5

### ISSUE THREAD

**Issue by fah** [OctoPrint/OctoPrint-FirmwareUpdater#223]
OctoPrint version : 1.3.12
OctoPi version    : 0.14.0

After installing this plugin octoprint service "exited" every time.

No found no reason in any log file. 

Then I tried:
```
$ sudo service octoprint stop
$ source ~/oprint/bin/activate
$ octoprint serve --debug --host 127.0.0.1
Traceback (most recent call last):
  File "/home/pi/oprint/bin/octoprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyserial>=3.4,<3.5
```

Log from this plugin installation procedure shows:</br>
~/.octoprint/logs/plugin_pluginmanager_console.log
```
2021-03-17 14:12:50,663   /home/pi/oprint/bin/python -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/archive/master.zip --no-cache-dir
2021-03-17 14:12:57,732 > Collecting https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/archive/master.zip
2021-03-17 14:12:58,737 > Downloading https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/archive/master.zip
2021-03-17 14:13:10,169 > Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-FirmwareUpdater==1.10.9)
2021-03-17 14:13:10,170 > Collecting pyserial>=3.5 (from OctoPrint-FirmwareUpdater==1.10.9)
2021-03-17 14:13:15,683 > Downloading https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90kB)
Requirement already satisfied: ...
...
2021-03-17 14:13:16,221 > Installing collected packages: pyserial, OctoPrint-FirmwareUpdater
2021-03-17 14:13:16,223 > Found existing installation: pyserial 3.4
2021-03-17 14:13:16,224 > Uninstalling pyserial-3.4:
2021-03-17 14:13:16,225 > Successfully uninstalled pyserial-3.4
2021-03-17 14:13:17,496 > Running setup.py install for OctoPrint-FirmwareUpdater: started
2021-03-17 14:13:21,505 > Running setup.py install for OctoPrint-FirmwareUpdater: finished with status 'done'
2021-03-17 14:13:22,510 > Successfully installed OctoPrint-FirmwareUpdater-1.10.9 pyserial-3.5
```

To solve this I tried:
```
$ pip uninstall pyserial
...
$ pip install pyserial==3.4
...
```
I did a  ```apt update & apt upgrade``` finally.

Octopi starts now, but this is no good way to install a plugin :-).

I actually tried not to change a running system by "just installing a plugin". :-)

What I expect:
1. Log message what goes wrong.
2. Depending on octopi version pyserial 3.4 or 3.5 or simply not forcing to 3.5 at all, if not needed.

**Comment by benlye** [comment]
Fair point - I've pretty sure pySerial 3.5 isn't really required - next version will be pyserial>=3.4 instead.
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/commit/831ecca3c9779d6887e1bb8b5f029d6d3b927a71
