### ISSUE TITLE
Error in Firmware Updater with BFT protocol after update Octoprint

### ISSUE THREAD

**Issue by mriscoc** [OctoPrint/OctoPrint-FirmwareUpdater#317]
After update Octoprint using
```bash
sudo apt upgrade
```

BFT is not working and these errors are written into the log file:
```
2022-07-03 00:25:28,129 - octoprint.plugins.firmwareupdater - INFO - Initializing Marlin BFT protocol
2022-07-03 00:25:28,131 - octoprint.plugins.firmwareupdater - INFO - pySerial Version: 3.5
2022-07-03 00:25:28,148 - octoprint.plugins.firmwareupdater - INFO - Attempting to delete previous firmware file /fw083722.bin
2022-07-03 00:25:28,638 - octoprint.plugins.firmwareupdater - INFO - Connecting to printer at '/dev/ttyUSB0' using Marlin BFT protocol
2022-07-03 00:25:28,639 - octoprint.plugins.firmwareupdater - INFO - Connecting: Switching Marlin to binary protocol...
2022-07-03 00:25:29,388 - octoprint.plugins.firmwareupdater - INFO - Connection synced [0], binary protocol version 0.1.0, 96 byte payload buffer
2022-07-03 00:25:29,389 - octoprint.plugins.firmwareupdater - INFO - Transfering file to printer using Marlin BFT '/tmp/tmpfu3od3fh' -> /fw002529.bin
2022-07-03 00:25:35,244 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Unable to transfer file.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_firmwareupdater/methods/marlinbft.py", line 105, in _flash_marlinbft
    filetransfer.copy(firmware, target, True, False)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 422, in copy
    self.write(data[start:end])
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 378, in write
    self.protocol._send(FileTransferProtocol.protocol_id, FileTransferProtocol.Packet.WRITE, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 223, in _send
    self._await_response()
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 243, in _await_response
    switch[token](data)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 292, in _response_ok
    raise SynchronizationError()
binproto2.exceptions.SynchronizationError
```
Plugin version: 1.13.3
Octopi version: 0.17.0
Python version: 3.7.3
Octoprint version: 1.8.1

**Comment by benlye** [comment]
I think you'll have to take that up with the BFT protocol developer.

**Comment by mriscoc** [comment]
Oh sorry, my mistake, I was thinking that I was in his Github.

**Comment by mriscoc** [comment]
New attempt

```
2022-07-04 15:19:28,155 - octoprint.plugins.firmwareupdater - INFO - Current Baud: 250000
2022-07-04 15:19:28,156 - octoprint.plugins.firmwareupdater - INFO - Initializing Marlin BFT protocol
2022-07-04 15:19:28,157 - octoprint.plugins.firmwareupdater - INFO - pySerial Version: 3.5
2022-07-04 15:19:28,196 - octoprint.plugins.firmwareupdater - INFO - Attempting to delete previous firmware file /fw083722.bin
2022-07-04 15:19:29,871 - octoprint.plugins.firmwareupdater - INFO - Connecting to printer at '/dev/ttyUSB0' using Marlin BFT protocol
2022-07-04 15:19:29,874 - octoprint.plugins.firmwareupdater - INFO - Connecting: Switching Marlin to binary protocol...
2022-07-04 15:19:29,890 - octoprint.plugins.firmwareupdater - INFO - Connection synced [0], binary protocol version 0.1.0, 96 byte payload buffer
2022-07-04 15:19:29,890 - octoprint.plugins.firmwareupdater - INFO - Transfering file to printer using Marlin BFT '/tmp/tmpxqj7m0t3' -> /fw151929.bin
2022-07-04 15:19:29,900 - octoprint.plugins.firmwareupdater - INFO - File Transfer version: 0.1.0, compression: heatshrink
2022-07-04 15:19:29,951 - octoprint.plugins.firmwareupdater - INFO - Opened file: fw151929.bin
2022-07-04 15:19:30,033 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.00% 9.62KiB/s [11.36KiB/s] Errors: 0
2022-07-04 15:19:30,042 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.05% 10.07KiB/s [11.89KiB/s] Errors: 0
2022-07-04 15:19:30,051 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.11% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,061 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.16% 10.15KiB/s [11.98KiB/s] Errors: 0
2022-07-04 15:19:30,072 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.21% 9.72KiB/s [11.47KiB/s] Errors: 0
2022-07-04 15:19:30,082 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.26% 9.64KiB/s [11.39KiB/s] Errors: 0
2022-07-04 15:19:30,090 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.32% 9.88KiB/s [11.66KiB/s] Errors: 0
2022-07-04 15:19:30,100 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.37% 9.84KiB/s [11.62KiB/s] Errors: 0
2022-07-04 15:19:30,109 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.42% 9.86KiB/s [11.64KiB/s] Errors: 0
2022-07-04 15:19:30,118 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.47% 9.92KiB/s [11.72KiB/s] Errors: 0
2022-07-04 15:19:30,127 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.53% 9.98KiB/s [11.78KiB/s] Errors: 0
2022-07-04 15:19:30,136 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.58% 10.02KiB/s [11.83KiB/s] Errors: 0
2022-07-04 15:19:30,145 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.63% 10.07KiB/s [11.89KiB/s] Errors: 0
2022-07-04 15:19:30,154 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.68% 10.10KiB/s [11.92KiB/s] Errors: 0
2022-07-04 15:19:30,162 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.74% 10.13KiB/s [11.96KiB/s] Errors: 0
2022-07-04 15:19:30,171 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.79% 10.15KiB/s [11.99KiB/s] Errors: 0
2022-07-04 15:19:30,180 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.84% 10.17KiB/s [12.01KiB/s] Errors: 0
2022-07-04 15:19:30,189 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.89% 10.20KiB/s [12.04KiB/s] Errors: 0
2022-07-04 15:19:30,198 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 0.95% 10.21KiB/s [12.06KiB/s] Errors: 0
2022-07-04 15:19:30,207 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.00% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,216 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.05% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,225 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.10% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,233 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.16% 10.28KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,242 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.21% 10.29KiB/s [12.15KiB/s] Errors: 0
2022-07-04 15:19:30,251 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.26% 10.30KiB/s [12.16KiB/s] Errors: 0
2022-07-04 15:19:30,260 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.31% 10.31KiB/s [12.17KiB/s] Errors: 0
2022-07-04 15:19:30,269 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.37% 10.32KiB/s [12.18KiB/s] Errors: 0
2022-07-04 15:19:30,278 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.42% 10.33KiB/s [12.19KiB/s] Errors: 0
2022-07-04 15:19:30,287 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.47% 10.33KiB/s [12.19KiB/s] Errors: 0
2022-07-04 15:19:30,296 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.52% 10.31KiB/s [12.17KiB/s] Errors: 0
2022-07-04 15:19:30,306 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.58% 10.30KiB/s [12.16KiB/s] Errors: 0
2022-07-04 15:19:30,315 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.63% 10.31KiB/s [12.18KiB/s] Errors: 0
2022-07-04 15:19:30,323 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.68% 10.32KiB/s [12.19KiB/s] Errors: 0
2022-07-04 15:19:30,332 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.73% 10.33KiB/s [12.19KiB/s] Errors: 0
2022-07-04 15:19:30,341 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.79% 10.33KiB/s [12.20KiB/s] Errors: 0
2022-07-04 15:19:30,350 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.84% 10.34KiB/s [12.21KiB/s] Errors: 0
2022-07-04 15:19:30,359 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.89% 10.34KiB/s [12.21KiB/s] Errors: 0
2022-07-04 15:19:30,368 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 1.94% 10.35KiB/s [12.22KiB/s] Errors: 0
2022-07-04 15:19:30,377 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.00% 10.35KiB/s [12.23KiB/s] Errors: 0
2022-07-04 15:19:30,386 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.05% 10.36KiB/s [12.23KiB/s] Errors: 0
2022-07-04 15:19:30,394 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.10% 10.36KiB/s [12.24KiB/s] Errors: 0
2022-07-04 15:19:30,403 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.15% 10.37KiB/s [12.25KiB/s] Errors: 0
2022-07-04 15:19:30,413 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.21% 10.36KiB/s [12.24KiB/s] Errors: 0
2022-07-04 15:19:30,423 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.26% 10.34KiB/s [12.21KiB/s] Errors: 0
2022-07-04 15:19:30,433 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.31% 10.31KiB/s [12.17KiB/s] Errors: 0
2022-07-04 15:19:30,443 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.36% 10.28KiB/s [12.14KiB/s] Errors: 0
2022-07-04 15:19:30,453 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.42% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,463 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.47% 10.24KiB/s [12.09KiB/s] Errors: 0
2022-07-04 15:19:30,472 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.52% 10.24KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,482 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.57% 10.22KiB/s [12.07KiB/s] Errors: 0
2022-07-04 15:19:30,491 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.63% 10.22KiB/s [12.07KiB/s] Errors: 0
2022-07-04 15:19:30,501 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.68% 10.21KiB/s [12.06KiB/s] Errors: 0
2022-07-04 15:19:30,511 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.73% 10.19KiB/s [12.03KiB/s] Errors: 0
2022-07-04 15:19:30,520 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.79% 10.20KiB/s [12.04KiB/s] Errors: 0
2022-07-04 15:19:30,529 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.84% 10.20KiB/s [12.05KiB/s] Errors: 0
2022-07-04 15:19:30,538 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.89% 10.21KiB/s [12.06KiB/s] Errors: 0
2022-07-04 15:19:30,547 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 2.94% 10.22KiB/s [12.06KiB/s] Errors: 0
2022-07-04 15:19:30,556 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.00% 10.22KiB/s [12.07KiB/s] Errors: 0
2022-07-04 15:19:30,564 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.05% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,573 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.10% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,582 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.15% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,591 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.21% 10.24KiB/s [12.09KiB/s] Errors: 0
2022-07-04 15:19:30,600 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.26% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,610 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.31% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,619 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.36% 10.24KiB/s [12.09KiB/s] Errors: 0
2022-07-04 15:19:30,628 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.42% 10.24KiB/s [12.09KiB/s] Errors: 0
2022-07-04 15:19:30,637 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.47% 10.24KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,646 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.52% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,654 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.57% 10.25KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,663 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.63% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,672 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.68% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,682 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.73% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,691 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.78% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,700 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.84% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,709 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.89% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,718 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.94% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,728 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 3.99% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,737 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.05% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,746 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.10% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,755 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.15% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,763 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.20% 10.27KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,772 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.26% 10.27KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,782 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.31% 10.25KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,791 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.36% 10.26KiB/s [12.11KiB/s] Errors: 0
2022-07-04 15:19:30,800 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.41% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,809 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.47% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,818 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.52% 10.27KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,827 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.57% 10.27KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,836 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.62% 10.28KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,844 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.68% 10.28KiB/s [12.14KiB/s] Errors: 0
2022-07-04 15:19:30,853 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.73% 10.28KiB/s [12.14KiB/s] Errors: 0
2022-07-04 15:19:30,862 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.78% 10.29KiB/s [12.15KiB/s] Errors: 0
2022-07-04 15:19:30,871 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.83% 10.29KiB/s [12.15KiB/s] Errors: 0
2022-07-04 15:19:30,880 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.89% 10.29KiB/s [12.15KiB/s] Errors: 0
2022-07-04 15:19:30,889 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.94% 10.29KiB/s [12.15KiB/s] Errors: 0
2022-07-04 15:19:30,898 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 4.99% 10.29KiB/s [12.16KiB/s] Errors: 0
2022-07-04 15:19:30,907 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.04% 10.29KiB/s [12.16KiB/s] Errors: 0
2022-07-04 15:19:30,917 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.10% 10.28KiB/s [12.14KiB/s] Errors: 0
2022-07-04 15:19:30,927 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.15% 10.27KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,936 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.20% 10.28KiB/s [12.13KiB/s] Errors: 0
2022-07-04 15:19:30,946 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.25% 10.26KiB/s [12.12KiB/s] Errors: 0
2022-07-04 15:19:30,957 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.31% 10.25KiB/s [12.10KiB/s] Errors: 0
2022-07-04 15:19:30,967 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.36% 10.24KiB/s [12.09KiB/s] Errors: 0
2022-07-04 15:19:30,977 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.41% 10.23KiB/s [12.08KiB/s] Errors: 0
2022-07-04 15:19:30,987 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.47% 10.22KiB/s [12.07KiB/s] Errors: 0
2022-07-04 15:19:30,997 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.52% 10.21KiB/s [12.06KiB/s] Errors: 0
2022-07-04 15:19:31,007 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.57% 10.21KiB/s [12.05KiB/s] Errors: 0
2022-07-04 15:19:31,016 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.62% 10.20KiB/s [12.04KiB/s] Errors: 0
2022-07-04 15:19:31,027 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.68% 10.19KiB/s [12.03KiB/s] Errors: 0
2022-07-04 15:19:31,037 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.73% 10.18KiB/s [12.02KiB/s] Errors: 0
2022-07-04 15:19:31,047 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.78% 10.17KiB/s [12.01KiB/s] Errors: 0
2022-07-04 15:19:31,057 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.83% 10.16KiB/s [12.00KiB/s] Errors: 0
2022-07-04 15:19:31,068 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.89% 10.14KiB/s [11.98KiB/s] Errors: 0
2022-07-04 15:19:31,082 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.94% 10.10KiB/s [11.92KiB/s] Errors: 0
2022-07-04 15:19:32,163 - octoprint.plugins.firmwareupdater - INFO - PROGRESS: 5.99% 5.04KiB/s [5.95KiB/s] Errors: 1
2022-07-04 15:19:32,168 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Unable to transfer file.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_firmwareupdater/methods/marlinbft.py", line 105, in _flash_marlinbft
    filetransfer.copy(firmware, target, True, False)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 422, in copy
    self.write(data[start:end])
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 378, in write
    self.protocol._send(FileTransferProtocol.protocol_id, FileTransferProtocol.Packet.WRITE, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 223, in _send
    self._await_response()
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 243, in _await_response
    switch[token](data)
  File "/home/pi/oprint/lib/python3.7/site-packages/binproto2/protocols.py", line 292, in _response_ok
    raise SynchronizationError()
binproto2.exceptions.SynchronizationError
```

**Comment by benlye** [comment]
That's still a BFT protocol error. This plugin only uses the protocol, it is maintained by someone else.

**Comment by benlye** [comment]
For what it's worth, I just updated my OctoPrint installation with with `sudo apt upgrade` and the BFT protocol is still working fine for me.  Whatever problem you have, I don't think the root cause is in the Firmware Updater plugin.

**Comment by mriscoc** [comment]
I did a test and init a transfer by hand:
```bash
 python ./transfer.py -p /dev/ttyUSB0 -b250000 -d 512 -c F.bin
```
and was successful, then, I'm lost.
![image](https://user-images.githubusercontent.com/2745567/177227158-decb4e73-9458-43ed-a824-d9ee744e514e.png)

**Comment by mriscoc** [comment]
For reference, I increase "Wait after connect" and "Communication timeout" values:

![image](https://user-images.githubusercontent.com/2745567/177231568-8a6b910e-a210-409d-b400-0bb33cdbd19f.png)

And the transfer is ok again.
