### ISSUE TITLE
I can't use the Firmware Updater plugin

### ISSUE THREAD

**Issue by luisr320** [OctoPrint/OctoPrint-FirmwareUpdater#362]
**Hardware Setup**
I have a Prusa iMK3S, with a Raspberry Pi 4B, which works fine. I can upload the Gcode from Prusa Slicer by Wifi to the Octoprint Server and the printer works fine.

**Describe the problem**

- I can upload the Gcode from Prusa Slicer by Wifi to the Octoprint Server and the printer works fine.
- I'm using the TX/TX connection between the Raspberry Pi and the Prusa board. On the RPi the serial port is identified as ttyAMA0.
- If I connect to the Rpi with putty, I can send a echo message to this port and I can see it displayed in the Octoprint console.
- I have the Baud rate set to Default, but I have tried all the individual baud rates set manually.
- I have uninstalled and reinstalled avrdude, and made the updates and upgrades.
- I'm running Octoprint 1.10.2 and the Firmware updater is version 1.14.1.
- I have downloaded the latest firmware for this printer directly from the Prusa site, with the name MK3_FW_3.14.0_MULTILANG.hex.
- The command line sent by the plugin is this: /usr/bin/avrdude -v -q -p m2560 -c wiring -P /dev/ttyAMA0 -D -U flash:w:/tmp/tmpt96e0c2x:i
- I tried disconnecting the octoprint server before trying to send the firmware, but it doesn't work either.

No matter what I do, I just can't flash the new firmware into the printer. I get the message "Starting flash...", it hangs for about 30 seconds and then i get a "Flashing failed; Timeout communicating with the programmer".

Please HELP!.
Thank you

**Log Files**

**Firmware updater log:**

2024-07-08 14:12:29,295 /usr/bin/avrdude -v -q -p m2560 -c wiring -P /dev/ttyAMA0 -D -U flash:w:/tmp/tmpnhg61777:i
2024-07-08 14:12:29,864 > 
2024-07-08 14:12:29,865 > avrdude: Version 6.3-20171130
2024-07-08 14:12:29,865 >          Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
2024-07-08 14:12:29,865 >          Copyright (c) 2007-2014 Joerg Wunsch
2024-07-08 14:12:29,866 > 
2024-07-08 14:12:29,866 >          System wide configuration file is "/etc/avrdude.conf"
2024-07-08 14:12:29,866 >          User configuration file is "/home/pi/.avrduderc"
2024-07-08 14:12:29,866 >          User configuration file does not exist or is not a regular file, skipping
2024-07-08 14:12:29,867 > 
2024-07-08 14:12:29,867 >          Using Port                    : /dev/ttyAMA0
2024-07-08 14:12:29,867 >          Using Programmer              : wiring
2024-07-08 14:12:29,867 > 
2024-07-08 14:12:32,785 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:32,786 > 
2024-07-08 14:12:36,794 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:36,795 > 
2024-07-08 14:12:40,803 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:40,805 > 
2024-07-08 14:12:44,812 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:44,813 > 
2024-07-08 14:12:48,820 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:48,821 > 
2024-07-08 14:12:52,830 > avrdude: stk500v2_ReceiveMessage(): timeout
2024-07-08 14:12:52,830 > avrdude: stk500v2_getsync(): timeout communicating with programmer
2024-07-08 14:12:52,831 > 
2024-07-08 14:12:52,832 > avrdude done.  Thank you.
2024-07-08 14:12:52,832 > 

**Octopi log:**

2024-07-08 12:48:27,506 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2024-07-08 12:48:27,527 - octoprint.plugins.octoeverywhere - INFO - Server con wss://lon.octoeverywhere.com/octoclientws[1] IS past it's RunFor time 2 days, 22:19:37.241884 and IS past it's time since last user activity 2 days, 22:19:34.540668
2024-07-08 12:48:27,527 - octoprint.plugins.octoeverywhere - INFO - Server con wss://lon.octoeverywhere.com/octoclientws[1] RunFor is complete and will be disconnected.
2024-07-08 12:48:27,528 - octoprint.plugins.octoeverywhere - INFO - Closing all open web stream sockets (0)
2024-07-08 12:48:27,528 - octoprint.plugins.octoeverywhere - INFO - OctoServerCon websocket close start. IsPrimary?:True; wsId:2530712144
2024-07-08 12:48:27,531 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2024-07-08 12:48:27,531 - octoprint.server - INFO - OctoPrint 1.10.2
2024-07-08 12:48:27,533 - octoprint.plugin.core - INFO - 34 plugin(s) registered with the system:
|  Achievements Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/achievements
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Bed Leveling Plugin (2.1.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_CR10_Leveling
|  Bed Visualizer (1.1.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_bedlevelvisualizer
|  Cancel Objects (0.5.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_cancelobject
|  Classic Webcam (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/classicwebcam
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Dashboard (1.19.11) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  Event Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/eventmanager
|  File Check (2024.3.27) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  FileManager (0.1.6) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_filemanager
|  Firmware Check (2021.10.11) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
|  Firmware Updater (1.14.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmwareupdater
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  ipOnConnect (0.2.4) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_ipOnConnect
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  OctoEverywhere! (3.4.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_octoeverywhere
|  Pi Support Plugin (2023.10.10) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  Printoid Plugin (1.2.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_printoid
|  Prusa Leveling Guide (1.0.18) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_PrusaLevelingGuide
|  Pushover (0.3.8) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pushover
|  Slicer Thumbnails (1.0.7) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_prusaslicerthumbnails
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Themeify (1.2.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_themeify
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
|  WiFi Status (1.9.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2024-07-08 12:48:27,599 - octoprint.plugins.octoeverywhere - INFO - Service websocket closed.
2024-07-08 12:48:27,616 - octoprint.plugins.octoeverywhere - INFO - OctoServerCon disconnect complete.
2024-07-08 12:48:27,671 - octoprint.plugins.octoeverywhere - INFO - Disconnected from OctoEverywhere, server con wss://lon.octoeverywhere.com/octoclientws[1]
2024-07-08 12:48:27,678 - octoprint.plugins.octoeverywhere - INFO - Closing all open web stream sockets (0)
2024-07-08 12:48:27,694 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|    cores: 4
|    freq: 1500.0
|    ram: 1909071872
|  os:
|    bits: 32
|    id: linux
|    platform: linux
|  plugins:
|    pi_support:
|      model: Raspberry Pi 4 Model B Rev 1.1
|      octopi_camera_stack: webcamd
|      octopi_version: 0.18.0
|      octopiuptodate_build: 0.18.0-1.8.6-20221018093204
|      octopiuptodate_build_short: 2022.10.18.093204
|      throttle_check_enabled: true
|      throttle_check_functional: true
|      throttle_state: '0x50000'
|  python:
|    pip: 20.3.3
|    version: 3.7.3
|    virtualenv: /home/pi/oprint
2024-07-08 12:48:27,695 - octoprint.server - INFO - ------------------------------------------------------------------------------
2024-07-08 12:48:27,684 - octoprint.plugins.octoeverywhere - INFO - Server con wss://lon.octoeverywhere.com/octoclientws[1] IS past it's RunFor time 2 days, 22:19:37.399298 and IS past it's time since last user activity 2 days, 22:19:34.698080
2024-07-08 12:48:27,750 - octoprint.plugins.octoeverywhere - INFO - Server con wss://lon.octoeverywhere.com/octoclientws[1] RunFor is complete, disconnected, and exiting the main thread.
2024-07-08 12:48:27,763 - octoprint.plugins.octoeverywhere - INFO - RepeatTimer thread exit
2024-07-08 12:48:27,784 - octoprint.plugins.octoeverywhere - INFO - Attempting to use lowest latency server: wss://lon.octoeverywhere.com/octoclientws
2024-07-08 12:48:27,825 - octoprint.plugins.octoeverywhere - INFO - Attempting to talk to OctoEverywhere, server con wss://lon.octoeverywhere.com/octoclientws[1] wsId:2505363408
2024-07-08 12:48:28,290 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 13, 'printer_state': 'OPERATIONAL'}
2024-07-08 12:48:28,535 - octoprint.plugins.octoeverywhere - INFO - Connected To OctoEverywhere, server con wss://lon.octoeverywhere.com/octoclientws[1]. Starting handshake...
2024-07-08 12:48:29,405 - octoprint.plugins.octoeverywhere - INFO - Handshake complete, server con wss://lon.octoeverywhere.com/octoclientws[1], successfully connected to OctoEverywhere!
2024-07-08 12:48:29,605 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'version': '1.10.2', 'os': 'linux', 'bits': 32, 'python': '3.7.3', 'pip': '20.3.3', 'cores': 4, 'freq': 1500.0, 'ram': 1909071872, 'pi_model': 'Raspberry Pi 4 Model B Rev 1.1', 'octopi_version': '0.18.0', 'octopiuptodate_build': '0.18.0-1.8.6-20221018093204', 'plugins': 'wifistatus:1.9.0,themeify:1.2.2,prusaslicerthumbnails:1.0.7,pushover:0.3.8,prusalevelingguide:1.0.18,printoid:1.2.1,iponconnect:0.2.4,firmwareupdater:1.14.1,filemanager:0.1.6,dashboard:1.19.11,cancelobject:0.5.0,octoeverywhere:3.4.3,bedlevelvisualizer:1.1.1,cr10_leveling:2.1.3', 'achievements': 'the_wizard,tgif,one_small_step_for_man,marathon,half_marathon,night_owl,all_beginnings_are_hard,so_close,the_manufacturer_i,early_bird'}
2024-07-08 12:48:32,755 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:48:32,756 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:48:32,774 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 127.0.0.1
2024-07-08 12:48:32,802 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:48:32,900 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:48:32,901 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:48:32,968 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:48:32,969 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:48:36,214 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:48:36,215 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:48:51,013 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:48:51,014 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:49:09,457 - octoprint.server.preemptive_cache - INFO - ... done in 44.90s
2024-07-08 12:49:09,459 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://octopi.local/', 'path': '/', 'query_string': 'l10n=en'}
2024-07-08 12:49:10,057 - octoprint.server.preemptive_cache - INFO - ... done in 0.60s
2024-07-08 12:49:10,716 - octoprint.plugins.octoeverywhere - INFO - Slipstream took 253220.50853395462 to fully update the cache
2024-07-08 12:49:14,336 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.204
2024-07-08 12:49:14,508 - octoprint.server.util.flask - INFO - Passively logging in user luisr320 from 192.168.1.204
2024-07-08 12:49:14,508 - octoprint.access.users - INFO - Logged in user: luisr320
2024-07-08 12:49:14,682 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2024-07-08 12:49:15,817 - octoprint.server.util.sockjs - INFO - User luisr320 logged in on the socket from client 192.168.1.204
2024-07-08 12:49:16,825 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.32s
2024-07-08 12:49:16,913 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
2024-07-08 12:49:17,308 - octoprint.plugins.tracking - INFO - Sent tracking event webui_load, payload: {'browser_name': 'Chrome', 'browser_version': '126.0.0.0', 'os_name': 'Windows', 'os_version': '10'}
2024-07-08 12:49:17,643 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.35s
2024-07-08 12:49:18,137 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.31s
2024-07-08 12:49:18,727 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.35s
2024-07-08 12:49:19,131 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2024-07-08 12:49:19,246 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.33s
2024-07-08 12:53:59,980 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Offline"
2024-07-08 12:54:00,029 - octoprint.server - INFO - Starting autorefresh of serial port list
2024-07-08 12:54:00,034 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2024-07-08 12:54:00,074 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Offline (luisr320)
2024-07-08 12:54:00,152 - octoprint.server - INFO - Serial port list was updated, refreshing the port list in the frontend
2024-07-08 12:54:03,708 - octoprint - ERROR - Exception on /api/plugin/appkeys [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask/app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/extension.py", line 1168, in _check_request_limit
    raise e
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/extension.py", line 1147, in _check_request_limit
    in_middleware,
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/extension.py", line 1022, in __filter_limits
    marked_for_limiting,
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/manager.py", line 102, in resolve_limits
    decorated_limits.extend(self.blueprint_limits(app, blueprint))
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/manager.py", line 185, in blueprint_limits
    app, blueprint
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/manager.py", line 250, in _blueprint_exemption_scope
    for k, f in self._blueprint_exemptions.items()
  File "/home/pi/oprint/lib/python3.7/site-packages/flask_limiter/manager.py", line 248, in <setcomp>
    ancestor_exemption = {
RuntimeError: dictionary changed size during iteration
2024-07-08 12:54:04,346 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2024-07-08 12:54:37,026 - octoprint.plugins.firmwareupdater - INFO - Firmware update profile index: 0
2024-07-08 12:54:37,036 - octoprint.plugins.firmwareupdater - INFO - Firmware update profile name: Default
2024-07-08 12:54:37,037 - octoprint.plugins.firmwareupdater - INFO - Printer port: /dev/ttyAMA0
2024-07-08 12:54:37,044 - octoprint.plugins.firmwareupdater - INFO - Flash method: avrdude
2024-07-08 12:54:37,067 - octoprint.plugins.firmwareupdater - INFO - Firmware update started
2024-07-08 12:54:37,092 - octoprint.plugins.firmwareupdater - INFO - Running '/usr/bin/avrdude -v -q -p m2560 -c wiring -P /dev/ttyAMA0 -D -U flash:w:/tmp/tmpr2_hqn_w:i' in /usr/bin
2024-07-08 12:55:02,986 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Timeout communicating with programmer.

**Additional context**
I keep getting the Udervoltage warning on Octoprint, but it works fine

**Comment by benlye** [comment]
avrdude isn't getting a response when it tries to connect to the port you've told it to use. 

I don't have this board but from what others have commented it looks like you're using the right avrdude settings, so the problem is probably in your config / wiring.

There's not really anything I can do to help - you're better off looking for a user group where someone might have a similar setup.

**Comment by benlye** [comment]
You might find something useful in https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/307. If you're using the RPi header you're probably going to have to wire up more pins and use `linuxgpio` instead of `wiring`. It seems like the RX/TX ports in that header can't be used to flash the MCU the way you're trying to do it.

**Comment by luisr320** [comment]
Thank you. I think that the problem I have is due to the connection between the Prusa board and the Rpi4 board being done trough the RX/TX Uart port. I think that the connection for the firmware updater to work must be done via USB

**Comment by flo269** [comment]
Hey, I am experiencing the same symptoms, with a different setup. I have the same versions installed as you, but I am connected via USB. I'm about to head out, but will upload logs etc. later or tomorrow. Just a quick heads up.

MK3s+ and no hardware or octopi changes since the last, flawlessly working, updates.

**Comment by luisr320** [comment]
So you are connecting the Rpi4 with the Prusa board using the USB ports?

**Comment by flo269** [comment]
Yes, I print with this setup all time and even today between the failed updates attempts. I haven't changed a thing (apart from Filament) in ages.
![Screenshot 2024-07-08 at 21 10 52](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/assets/25147331/f0dad486-31ad-4875-86e1-f540dc1b1f74)

**Comment by luisr320** [comment]
Ok, so finally i figured it out. I was trying to use the TX/RX ports of both the Rpi4 and the Einsy Board, and even though it works for transferring the gcode from PrusaSlicer to the printer via Wifi, it wont work for the firmware updater. For that, I connected the Einsy Board USB port directly to one of the the Rpi4 USB ports, which created a new tty device named ACM0, and by leaving all the setups options as default, I managed to update the new firmware remotely.  Hurray!!!
Try leaving the baudrate in AUTO, and use the "wiring" connection

**Comment by flo269** [comment]
Great to hear that it works for you.
I tried auto baudrate and "wiring" connection is set and used as before. I'm still stuck.

@anyone Anything else I could do that might be helpful to find out what's going on? Thanks! :-)

**Comment by flo269** [comment]
I just remembered that I had installed "[Octoprint-PrusaResetMode](https://github.com/jacopotediosi/Octoprint-PrusaResetMode)" a while back. That was what was blocking the connection. I disabled it and then everything worked flawlessly...

Sorry for the noise!!
